### ISSUE TITLE
Input not cleared after adding "free" tag with typeaheadjs enabled

### ISSUE THREAD

**Issue by fbacall** [bootstrap-tagsinput/bootstrap-tagsinput#331]
When adding a non-typeahead tag into a tags-input field with typeaheadjs enabled, the entered text reappears next to the newly created tag when the input element loses focus.

To reproduce:
1. Go to the "Typeahead" example here: http://timschlechter.github.io/bootstrap-tagsinput/examples/
2. Type "hello" into the input and press enter
3. Click outside the input

**Comment by mediavrog** [comment]
+1

**Comment by psenechal** [comment]
+1

**Comment by matopeter** [comment]
Same here on FF 37.0.1 and Chromium 41. You can try it here: http://jsfiddle.net/4Lj77/
If you have a working version, please create a JSFiddle or give us a js lib version list! Thanks.

**Comment by nathan-fig** [comment]
+1. Fixed by replacing lines 350-359 with:

      if (self.options.addOnBlur && self.options.freeInput) {
        self.$input.blur($.proxy(function () {
          self.add(self.$input.val());
          self.$input.val('');
        }, self));
      }

**Comment by guibirow** [comment]
+1
To fix, update the line 303 with the following:
```
updater: function (text) {
             self.add(this.map[text]);
             return ''; //this is the trick
           },
```

**Comment by xplicit** [comment]
@guibirow this does not fix the issue when freeInput is disabled, user typed few letters but did not select the tag and then focused out from the control.

**Comment by xplicit** [comment]
for bootstrap3-typeahead the fix which works for me:

lines 324-328:

        if (!self.options.freeInput) {
	        self.$input.on('focusout', $.proxy(function(event) {
    	    	self.$input.val('');
        	}, self));
        }

**Comment by MikalJ** [comment]
Tagsinput clears the input field correctly. Typeahead, however, contains a feature that removes text suggested by typeahead, as the field looses focus, and returns the last value entered by the user. It doesn't take into account, if the input field has been manipulated in the meantime though.

The solution is to clear the value of typeahead, as tagsinput clears the input field.

At line line 433 in bootstrap-tagsinput.js
```javascript
if (self.options.freeInput && (keyCombinationInList(event, self.options.confirmKeys) || maxLengthReached)) {
    self.add(maxLengthReached ? text.substr(0, self.options.maxChars) : text);
    $input.val('');
    event.preventDefault();
}
```
Change it to:
```javascript
if (self.options.freeInput && (keyCombinationInList(event, self.options.confirmKeys) || maxLengthReached)) {
    self.add(maxLengthReached ? text.substr(0, self.options.maxChars) : text);
    $input.val('');
    if ($input.typeahead) {
        $input.typeahead('val', '');
    }
    event.preventDefault();
}
```
